### ISSUE TITLE
Metadata section tree should mirror neo object structure

### ISSUE THREAD

**Issue by achilleas-k** [G-Node/python-neo-nixio#14]
For example, the metadata section of a Group object should be a child of the metadata section of the parent Block.

Currently, all metadata sections are created in the root of the nix file.

**Comment by achilleas-k** [comment]
From the mapping description:
> A metadata section is only created for a NIX object if necessary, i.e., it is not created if the Neo object attributes are not set.

If the metadata structure is going to mirror the object structure, then all objects should have a metadata section, even if it's empty, to reference the child's section.

**Comment by stoewer** [comment]
> If the metadata structure is going to mirror the object structure, then all objects should have a metadata section, even if it's empty, to reference the child's section.

Or the section of the parent must be created when metadata is attached to the child entity.

**Comment by achilleas-k** [comment]
The path issue I mention in [this comment](https://github.com/G-Node/python-neo-nixio/pull/10#issuecomment-175563182) keeps rearing its ugly head.

In the case of your suggestion, it becomes necessary to know the full path at any given time during construction of the NIX object tree. For example, if a deep child object (e.g., a `DataArray` at `/Block/Segment/AnalogSignal/`) becomes the first to require a metadata section, the full path to that object is required in order to build the metadata tree from the root down. I'm not sure if this is a realistic scenario, but it's certainly not an invalid one.

Currently, when creating an object, we have access to its parent since we create objects from the root of the file downwards. I'm going to switch to keeping a `path` variable, which is passed down through the creation methods and can be used to backtrack up through the tree from any point in the creation of an object. This is will also be useful for the future plan to support partial writing.

The path would be a `/` delimited string of object names, starting from the root of the file.

What do you think?

**Comment by achilleas-k** [comment]
An alternative would be to keep the path as a list of tuples of the form `(nixtype, name)`, e.g., `[(block, block_one), (group, group_one)]`. This would make it more straightforward to follow the path of objects from the root down without checking all the containers of block for the object with the specific name.

This also gets around a problem I foresee with the original method: Assuming the path `/foo/bar`, if there are two objects named `bar` under `foo` of different types, the path becomes ambiguous. This is possible if Block `foo` has a child Source and a child DataArray, both named `bar`, which is not invalid.

**Comment by achilleas-k** [comment]
This is now implemented in the writer, but it's not fully tested. I need to write a test that traverses the data and metadata tree simultaneously checking for a one-to-one mapping along the way.
