### ISSUE TITLE
Signal grouping via metadata sections - possibly unnecessary?

### ISSUE THREAD

**Issue by achilleas-k** [G-Node/python-neo-nixio#16]
In the section on `neo.Segment` in the [mapping](https://github.com/G-Node/python-neo-nixio/blob/master/mapping.md#neosegment) file, we specified that `DataArray` objects created from a conversion of the same `AnalogSignal` or `IrregularlySampledSignal` objects should be grouped by sharing references to the same metadata segment.

Quoting from the mapping file:
> Signal objects in Neo can be grouped, e.g., `Segment.analogsignals` is a list of `AnalogSignal` objects, each of which can hold multiple signals. In order to be able to reconstruct the original signal groupings, all `DataArray` objects that belong to the same `AnalogSignal` (or `IrregularlySampledSignal`) have their metadata attribute point to the same Section.

**However**, `DataArrays` can also hold multiple signals. The data contained in the object can be a 2D array. More importantly, it seems like the restrictions and guidelines for what signals can coexist in a `DataArray` or an `AnalogSignal` (or `IrregularlySampledSignal`) are the same: Grouped signals must share the same time dimension.

Am I missing something? When we were designing the mappings, I think I was under the impression that `DataArray` data is 1-dimensional and therefore multiple arrays would have to be created per `AnalogSignal`. Since this is not the case, the grouping via metadata would be unnecessary.

**Comment by stoewer** [comment]
By just looking at the plain data, multiple signals from one neo Analogsignal would actually fit in one single DataArray. But regarding other data such as certain relationships a clean mapping from neo to NIX would not be possible if multiple signals were stored in such way.

**Comment by achilleas-k** [comment]
Understood.

I'll keep this issue open until it's done properly, with one signal per DataArray and grouping via metadata.

**Comment by achilleas-k** [comment]
PR #20.
