### ISSUE TITLE
Create unique names for NIX objects

### ISSUE THREAD

**Issue by achilleas-k** [G-Node/python-neo-nixio#19]
Unlike NIX object names, Neo object names are not required to be unique. Name conflicts can be resolved by appending an incrementing number to the common names.

Should this be done in a way that's reversible? If it needs to be reversible, perhaps a unique number (.e.g, the object's id) can be added to the NIX name even when there's no conflict.

**Comment by stoewer** [comment]
If by reversible you mean that a NEO object without a name will still have no name when it is read again from the NIX file, I would say this is not necessary.

NEO objects without name or even with duplicated names are a dumb "feature" anyway. Therefore it is IMHO not worth to be preserved :-)

**Comment by achilleas-k** [comment]
Well by reversible I meant that and also the following case:
- 2 Neo Blocks with the same name "block_name"
- We write them to a NIX file as "block_name.1" & "block_name.2" (for example)

The question is whether after conversion from NIX back to Neo, the renaming should be reversed, so that the two Neo blocks are named "block_name" again.

I suppose the real question is whether it matters--whether there are cases where name clashes are used to indicate anything about the two objects.

**Comment by stoewer** [comment]
> I suppose the real question is whether it matters--whether there are cases where name clashes are used to indicate anything about the two objects.

No, I don't think that reversibility is needed in this case. Maybe it's even better to keep the generated names.

**Comment by achilleas-k** [comment]
PR #20.
