### ISSUE TITLE
Relationship between RCG and Units after conversion to NIX

### ISSUE THREAD

**Issue by achilleas-k** [G-Node/python-neo-nixio#34]
Below, I use `A > B` to mean that `A` contains `B`, and `A -> B` to mean that A holds a reference to B.
Also `C(D)` means that `C` is a NIX object created from Neo object `D`.

Currently, when writing a `RecordingChannelGroup` that contains `Unit`s, the relationship is maintained in NIX by creating a `Source` object to represent the RCG and child `Source` objects to represent the units. So the original structure in Neo being
```
RCG > Unit -> SpikeTrain
```
becomes
```
Source(RCG) > Source(Unit) <- MultiTag(SpikeTrain)
```

In the original specification, `Source` objects that represent units are associated with the original parent RCG by both being referenced by the same `MultiTag` spiketrain. In other words, the same original structure mentioned above would become
```
MultiTag(SpikeTrain) -> Source(RCG)
                    `-> Source(Unit)
```

Both of these mappings can cause issues, though the latter has a much bigger issue than the former.

In the first case, there's the issue that we create `Source` objects as children of an RCG to represent individual recording channels. These `Source(RecordingChannel)` objects are created in the same container as the `Source(Unit)` objects. We do similar things in other parts of the mapping, for example where `MultiTag`s inside `Group` objects can represent either an `Epoch`, `Event`, or `SpikeTrain`. However, in these cases the grouping makes sense. `Epochs`, `Events`, and `SpikeTrains` share a lot of common characteristics (namely they point towards time instances or periods that are of some importance in the accompanying signals). A `Unit` is a very different entity from a `RecordingChannel`, so here we have a conceptual problem.

In the second case, the problem arises when there is no `SpikeTrain` in the original Neo object. I don't know if this is an actual use case, if a `Unit` can exist in a `RecordingChannelGroup` without it being a `SpikeTrain` container. It's possible that this should be an invalid case, because a Unit doesn't need to exist in the data for any other reason other than to group spiketrains, or it might be that there are cases where a Unit can exist in the datafile to indicate that it was recorded from but it emitted no spikes.

The Neo documentation clearly states that a Unit is a SpikeTrain container, but this is not enforced in any way, as is common for Neo, i.e., an empty Unit can exist.

**Comment by achilleas-k** [comment]
I'm going to change the implementation to match the original specification. If a Unit exists that does not contain any SpikeTrains, it will simply not be referenced by any other object and will only be accessible from the root Block object.

**Comment by stoewer** [comment]
> object to represent the RCG and child Source objects to represent the units. 

Channels not units, right?

**Comment by achilleas-k** [comment]
Well, the problem was that it was doing both. Both Channels and Units were converted to Source objects that were children of the RCG. I've changed it now so that it fits the original specification.

**Comment by twachtler** [comment]
> If a Unit exists that does not contain any SpikeTrains, it will simply not be referenced by any other object and will only be accessible from the root Block object.

In this case, it will not be possible to restore the original Neo structure by reading the NIX file. If in Neo the unit belongs to a RCG, that information should be kept somehow.

I don't see it as a problem to have both Units and RCs as children of RCG.

**Comment by achilleas-k** [comment]
I agree. It's certainly not a problem compared to losing information. I'll change the mapping spec and change the writer (and WIP reader) accordingly.

**Comment by achilleas-k** [comment]
Closing. PR #36.
