### ISSUE TITLE
Semantics of `file_origin` in neo

### ISSUE THREAD

**Issue by stoewer** [G-Node/python-neo-nixio#6]
Find out whether `file_origin` of neo objects represents the file of the original recording (in this case `file_origin` has to be stored within the current file) or whether it just represents the file the neo object was read from (in this case it is not necessary to store it).

**Comment by achilleas-k** [comment]
In all other IOs, the `file_origin` attribute is set as the (base)name of the file being read.
Storing it in the NIX file during write, and restoring it from the stored value, is unnecessary. It's purpose seems to be to act as a simple reference to the file origin of the data after they've been read from an IO.
